### ISSUE TITLE
Send to multiple hosts

### ISSUE THREAD

**Issue by lkraav** [drbrain/ruby-growl#4]
From my server I'm sending all my notifications to multiple devices: laptop (+vpn ip), desktop (+vpn ip), mobile (+vpn ip). If I just loop over a hostlist in shell script, that means six growl launches per every notification. Growl could also be used to selectively send messages to even a wider range of an audience, in which case we might be talking tens of process launches.

I'm pretty sure the most optimal approach is some option to pass multiple hostnames or a file with them and send these messages in one shot to all hosts from ruby-growl.
1. Any further and/or different thoughts?
2. Will you accept a patch for it?

**Comment by drbrain** [comment]
I looked into this, but it is too clumsy to handle errors properly so that you know which host has the bad connection.

Instead of using a shell script you should use a ruby script to drive the API directly for each of your hosts.  This will let you handle the errors exactly how you need them to be handled.  I think this will work for you:

``` ruby
#! /usr/bin/env ruby
require 'ruby-growl'

hosts = %w[
  192.0.2.1
  192.0.2.2
  192.0.2.3
]

app_name = 'my_app'
app_notifies = %w[type]

hosts.each do |host|
  g = Growl.new host, app_name, app_notifies
  g.notify 'type', 'title', 'message'
end
```

**Comment by lkraav** [comment]
True, direct API is an option here.

Other than that, I don't really consider delivery-reliability an issue. Fire & forget should be good enough for most cases, esp. with UDP.

**Comment by drbrain** [comment]
Growl 1.3 no longer supports UDP notifications, so for (upcoming) TCP support I don't think "because UDP"  is the best argument.

Also, while missed notifications may be OK for you, I don't want to force that on everyone, nor do I want to limit my choices

**Comment by lkraav** [comment]
True, forgot about them losing UDP. Anyway, fair enough, I got solutions out of this.
